# services:
#   postgres:
#     image: postgres:latest
#     container_name: postgres_api
#     restart: always
#     environment:
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB: ${DB_NAME}
#     ports:
#       - "${DB_PORT}:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data

#   redis:
#     image: redis:latest
#     container_name: redis_api
#     restart: always
#     command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis_data:/data

# volumes:
#   db_data:
#   redis_data:
services:
  # postgres:
  #   image: postgres:latest
  #   container_name: postgres_api
  #   restart: always
  #   environment:
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #   ports:
  #     - "${DB_PORT}:5432"
  cockroach:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb
    command: start-single-node --insecure
    ports:
      - "26257:26257"  # SQL
      - "8080:8080"    # Admin UI
    volumes:
      - cockroach-data:/cockroach/cockroach-data

  redis:
    image: redis:latest
    container_name: redis_api
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter
    restart: always
    environment:
      - REDIS_ADDR=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "9121:9121"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
  cockroach-data: