global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
  - job_name: 'cockroachdb'
    metrics_path: /_status/vars  # <-- FIXED path
    static_configs:
      - targets: ['cockroach:8080']